country_dict = {
 'global': 'GLOBAL',
 'argentina': 'AR',
 'australia': 'AU',
 'austria': 'AT',
 'belarus': 'BY',
 'belgium': 'BE',
 'bolivia': 'BO',
 'brazil': 'BR',
 'bulgaria': 'BG',
 'canada': 'CA',
 'chile': 'CL',
 'colombia': 'CO',
 'costa rica': 'CR',
 'cyprus': 'CY',
 'czech republic': 'CZ',
 'denmark': 'DK',
 'dominican republic': 'DO',
 'ecuador': 'EC',
 'egypt': 'EG',
 'el salvador': 'SV',
 'estonia': 'EE',
 'finland': 'FI',
 'france': 'FR',
 'germany': 'DE',
 'greece': 'GR',
 'guatemala': 'GT',
 'honduras': 'HN',
 'hong kong': 'HK',
 'hungary': 'HU',
 'iceland': 'IS',
 'india': 'IN',
 'indonesia': 'ID',
 'ireland': 'IE',
 'israel': 'IL',
 'italy': 'IT',
 'japan': 'JP',
 'kazakhstan': 'KZ',
 'latvia': 'LV',
 'lithuania': 'LT',
 'luxembourg': 'LU',
 'malaysia': 'MY',
 'mexico': 'MX',
 'morocco': 'MA',
 'netherlands': 'NL',
 'new zealand': 'NZ',
 'nicaragua': 'NI',
 'nigeria': 'NG',
 'norway': 'NO',
 'pakistan': 'PK',
 'panama': 'PA',
 'paraguay': 'PY',
 'peru': 'PE',
 'philippines': 'PH',
 'poland': 'PL',
 'portugal': 'PT',
 'romania': 'RO',
 'saudi arabia': 'SA',
 'singapore': 'SG',
 'slovakia': 'SK',
 'south korea': 'KR',
 'spain': 'ES',
 'sweden': 'SE',
 'switzerland': 'CH',
 'taiwan': 'TW',
 'thailand': 'TH',
 'turkey': 'TR',
 'ukraine': 'UA',
 'united arab emirates': 'AE',
 'united kingdom': 'GB',
 'united states': 'US',
 'uruguay': 'UY',
 'venezuela': 'VE',
 'vietnam': 'VN'}
